### ISSUE TITLE
GoCD Slack plugin does not show console log, or material change in latest gocd version.

### ISSUE THREAD

**Issue by atifsaddique211f** [ashwanthkumar/gocd-slack-build-notifier#76]
Hi         
I am using gocd version `17.4.0`.      
gocd-slack plugin version : `v1.4.0-RC11`      
But slack notification plugin does not show console or material change logs when sending notification.              
Error : `(Couldn't fetch build details; see server log.)` .       
Error : `(Couldn't fetch changes; see server log.)` .       

There is one more issue, I am getting notification a lot later the build has run, It has been 15 minutes the build was run successfully, but I am getting notification for each stage after 5 or 10 minutes.

Screenshot is also attached for reference.

<img width="1018" alt="screen shot 2017-10-17 at 6 54 09 pm" src="https://user-images.githubusercontent.com/8865972/31668956-10ecb336-b36d-11e7-9630-5f480a7f2b9d.png">

**Comment by ashwanthkumar** [comment]
@atifsaddique211f Can you please check the plugin logs on the server? They would be along side the server logs generally. It would be of the name `plugin-slack.notifier.log` or something similar. It might have additional information on why it's not able to fetch the build details. 

Some possible causes I can think of are 
1. Wrong/Incorrect credentials (login and password) in the `go_notify.conf`
2. Wrong/Incorrect `api-server-host` in the configuration file
3. Wrong/Incorrect proxy information

Regarding the late delivery, the plugin doesn't do any kind of throttling on it's side. It could be because the notifications are being delivered late by GoCD or the slack is throttling the requests we're sending (may be you've a lot of pipelines and enabled alerts for all of them which slack is throttling on it's side? Not sure though)

**Comment by ashwanthkumar** [comment]
Closing this. If you're still facing any issues, please feel free to open a new issue or re-open the same issue.
