### ISSUE TITLE
Display notifications for changes according to whitelist

### ISSUE THREAD

**Issue by zayyeh** [ashwanthkumar/gocd-slack-build-notifier#85]
GoCD correctly triggers pipeline according to my material whitelist, but plugin lists all changes for this repository, while ideally it should list only those matching whitelist. Could you guide me how to add this feature?

**Comment by ashwanthkumar** [comment]
@zayyeh The top changes for each material are the ones that already passed the whitelist or blacklist filters. Is there a more specific reason to just filter them further on the already truncated list of items of changes?

Also AFAIK even GoCD doesn't show just the whitelist changes while showing the changes isn't?

**Comment by pavelkostyurin** [comment]
Thanks for the answer.

Yeah, GoCD shows all changes, that's why I'm asking about possibility of getting only whitelist changes.

We could have tons of commits to the repository, but for the pipeline only several (whitelist) changes matter, and I want to display only them or not display anything at all, because otherwise it's confusing as it doesn't belong to that pipeline.

**Comment by ashwanthkumar** [comment]
If you want to restrict what you see on the GoCD Dashboard this plugin can't help you. This plugin only deals with what get's displayed on the slack message. 

What I proposed was, a pipeline wouldn't run until there's a whitelist / blacklist match in the first place. When the pipeline runs the top or top-N commits are already related to the changes that this pipeline was tracking. So doing a filter on top of that is something I feel a little un-necessary.

**Comment by pavelkostyurin** [comment]
If only I knew how to calculate N...

Anyway, thanks for the help, please, close the ticket.
